when:
  - event: [push, manual]
    branch: main

steps:
  build:
    image: alpine:edge
    commands:
      - apk update && apk add openssh-client shadow-login
      - mkdir -p /root/.ssh
      - echo "$KEY" > /root/.ssh/id_ed25519
      - chmod 0600 /root/.ssh/id_ed25519
      - ssh -i /root/.ssh/id_ed25519 -P $PORT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $USERNAME@$HOST "$COMMAND"
    when:
      event: [push, manual]
    environment:
      HOST:
        from_secret: host
      USERNAME:
        from_secret: username
      PORT:
        from_secret: port
      KEY:
        from_secret: key
      COMMAND:
        from_secret: command
